### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by xjsender** [mailtoharshit/awesome-browser-extensions-for-salesforce#4]
Link url for [Lighting Components Inspector](https://github.com/mailtoharshit/awesome-browser-extensions-for-salesforce#salesforce-lighting-components-inspector-) is not correct

![image](https://cloud.githubusercontent.com/assets/1450977/11863046/9fa9ea6a-a4cb-11e5-95c7-b3a3cd7fbc28.png)

**Comment by mailtoharshit** [comment]
Fixed !

**Comment by xjsender** [comment]
@mailtoharshit , thanks, quick response.
