### ISSUE TITLE
Can I add a PR for "Salesforce Dev Tools" chrome extension

### ISSUE THREAD

**Issue by xgeek-net** [mailtoharshit/awesome-browser-extensions-for-salesforce#9]
Hi, there.

Can I add a PR for "Salesforce Dev Tools" chrome extension?
Which is a free chrome extension I published at here : 
https://chrome.google.com/webstore/detail/salesforce-dev-tools/ehgmhinnhggigkogkbhnbodhbfjgncjf

And the detail about it you can check out my post:
https://www.xgeek.net/salesforce/tesforce-for-google-chrome/

Thanks!

@mailtoharshit

**Comment by mailtoharshit** [comment]
fork and send pull request

**Comment by xgeek-net** [comment]
My PR is here : https://github.com/mailtoharshit/awesome-browser-extensions-for-salesforce/pull/10 , thanks!

**Comment by mailtoharshit** [comment]
Merged !
